name: Auto Check Commit

on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create check run
        uses: actions/github-script@v6
        with:
          script: |
            const { data: checkRun } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Auto Check',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Auto Check',
                summary: '✅ Commit successfully checked.'
              }
            });
            console.log('Check run created:', checkRun.id);