name: Auto Check Commit

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append checkmark to log
        run: |
          echo "✅ Commit $(git rev-parse HEAD)" >> commit-checks.md

      - name: Commit and push log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add commit-checks.md
          git commit -m "Auto check for commit $(git rev-parse --short HEAD)" || echo "No changes to commit"
          git push